"""add name for artist and venue in show

Revision ID: 6354a06c8d7f
Revises: d75593f84429
Create Date: 2023-07-01 17:14:52.641039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6354a06c8d7f'
down_revision = 'd75593f84429'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('venue_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.drop_column('venue_name')
        batch_op.drop_column('artist_name')

    # ### end Alembic commands ###
