"""empty message

Revision ID: 674858926c66
Revises: 270624f8bd53
Create Date: 2023-06-28 01:06:41.287216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '674858926c66'
down_revision = '270624f8bd53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_upcoming_shows', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_column('num_upcoming_shows')

    # ### end Alembic commands ###
