"""add website in Venue

Revision ID: 7dbb2d4ddd09
Revises: e6cadcf80fa6
Create Date: 2023-06-28 23:19:33.675621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dbb2d4ddd09'
down_revision = 'e6cadcf80fa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_column('website')

    # ### end Alembic commands ###
