"""add show type to Show

Revision ID: adf08dbb953f
Revises: cb7bf67bd741
Create Date: 2023-07-01 16:35:44.685923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adf08dbb953f'
down_revision = 'cb7bf67bd741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_type', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.drop_column('show_type')

    # ### end Alembic commands ###
